package com.mycompany.knockknockclient;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

import javax.swing.JOptionPane;

/**
 * @brief Clase VistaCliente que representa la vista de un cliente que se conecta a un servidor
 * @author belen
 */
public class VistaCliente extends javax.swing.JFrame {

    private CristofyClient cliente;
    private LeerServidorThread thr;
    private Controlador controlador;

    /**
     * @brief Constructor por defecto de la clase VistaCliente
     */
    public VistaCliente() {
        setCliente(new CristofyClient());
        setControlador(new Controlador());
        initComponents();
        jPanelProgresoDescarga.setVisible(false);
        jTextFieldIP.setText("localhost");
        jPanelDetallesArtista.setVisible(false);
    }

    //Setters y Getters

    /**
     * @brief   Setter del atributo cliente. 
     *          Establece el cliente que se conecta al servidor
     * @param cliente   Cliente que se conecta al servidor
     */
    public void setCliente(CristofyClient cliente) {
        this.cliente = cliente;
    }

    /**
     * @brief   Getter del atributo cliente. 
     *          Devuelve el cliente que se conecta al servidor
     * @return  Cliente que se conecta al servidor
     */
    public CristofyClient getCliente() {
        return cliente;
    }

    /**
     * @brief   Setter del atributo thr. 
     *          Establece el hilo que lee los mensajes del servidor
     * @param thr   Hilo que lee los mensajes del servidor
     */
    public void setThr(LeerServidorThread thr) {
        this.thr = thr;
    }

    /**
     * @brief   Getter del atributo thr. 
     *          Devuelve el hilo que lee los mensajes del servidor
     * @return  Hilo que lee los mensajes del servidor
     */
    public LeerServidorThread getThr() {
        return thr;
    }

    /**
     * @brief   Setter del atributo controlador. 
     *          Establece el controlador que se encarga de generar las cadenas de login
     * @param controlador   Controlador que se encarga de generar las cadenas de login
     */
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    /**
     * @brief   Getter del atributo controlador. 
     *          Devuelve el controlador que se encarga de generar las cadenas de login
     * @return  Controlador que se encarga de generar las cadenas de login
     */
    public Controlador getControlador() {
        return controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneConexion = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        buttonEnviar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldContrasenia = new javax.swing.JTextField();
        jTextFieldLogin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonDesconectar = new javax.swing.JButton();
        jTextFieldIP = new javax.swing.JTextField();
        jTextFieldPuerto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonConectar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMensajesRecibidos = new javax.swing.JTextArea();
        jTextFieldMensajeEnviar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonVerUsuariosConectados = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsuariosConectados = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCancionesSistema = new javax.swing.JTable();
        jButtonVerCancionesSistema = new javax.swing.JButton();
        jButtonEscucharCancion = new javax.swing.JButton();
        jPanelProgresoDescarga = new javax.swing.JPanel();
        jLabelDescargando = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelPorciento = new javax.swing.JLabel();
        jProgressBarDescargaCancion = new javax.swing.JProgressBar();
        jTextFieldCadenaBusquedaCancion = new javax.swing.JTextField();
        jButtonBuscarCancionPorTexto = new javax.swing.JButton();
        jButtonVerDetallesArtista = new javax.swing.JButton();
        jPanelDetallesArtista = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabelNombreArtista = new javax.swing.JLabel();
        jButtonStopCancion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClose(evt);
            }
        });

        buttonEnviar.setText("Enviar");
        buttonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnviarActionPerformed(evt);
            }
        });

        jLabel3.setText("Introduzca su mensaje:");

        jLabel4.setText("Mensajes recibidos:");

        jLabel5.setText("Login");

        jLabel6.setText("Contraseña");

        jTextFieldContrasenia.setText("belen_robustillo");

        jTextFieldLogin.setText("belen_robustillo");
        jTextFieldLogin.setToolTipText("");

        jButton1.setText("Acceder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonDesconectar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonDesconectar.setText("Desconectar");
        jButtonDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesconectarActionPerformed(evt);
            }
        });

        jTextFieldPuerto.setText("6969");

        jLabel1.setText("IP");

        jLabel2.setText("Puerto");

        buttonConectar.setText("Conectar");
        buttonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConectarActionPerformed(evt);
            }
        });

        jTextAreaMensajesRecibidos.setColumns(20);
        jTextAreaMensajesRecibidos.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMensajesRecibidos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(165, 165, 165)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFieldIP)
                                                .addComponent(jTextFieldPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(38, 38, 38)
                                            .addComponent(buttonConectar))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldMensajeEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(34, 34, 34)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonDesconectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(buttonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldLogin)
                                        .addComponent(jTextFieldContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonConectar)
                        .addComponent(jButtonDesconectar)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMensajeEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEnviar))
                .addGap(68, 68, 68)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneConexion.addTab("Conexión y comunicación", jPanel1);

        jButtonVerUsuariosConectados.setText("Ver usuarios conectados");
        jButtonVerUsuariosConectados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerUsuariosConectadosActionPerformed(evt);
            }
        });

        jTableUsuariosConectados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Login", "Nombre", "Apellidos", "Playlists", "Canciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableUsuariosConectados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVerUsuariosConectados, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButtonVerUsuariosConectados)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneConexion.addTab("Usuarios conectados", jPanel2);

        jTableCancionesSistema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Título", "Autor", "Nº reproducciones", "Nº veces incluida en playlists"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCancionesSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCancionesSistemaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableCancionesSistema);

        jButtonVerCancionesSistema.setText("Ver canciones sistema");
        jButtonVerCancionesSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerCancionesSistemaActionPerformed(evt);
            }
        });

        jButtonEscucharCancion.setText("Escuchar");
        jButtonEscucharCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscucharCancionActionPerformed(evt);
            }
        });

        jLabelDescargando.setText("Descargando...");

        jLabelNumero.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelNumero.setText("0");

        jLabelPorciento.setText("%");
        jLabelPorciento.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanelProgresoDescargaLayout = new javax.swing.GroupLayout(jPanelProgresoDescarga);
        jPanelProgresoDescarga.setLayout(jPanelProgresoDescargaLayout);
        jPanelProgresoDescargaLayout.setHorizontalGroup(
            jPanelProgresoDescargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgresoDescargaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProgresoDescargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBarDescargaCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelProgresoDescargaLayout.createSequentialGroup()
                        .addComponent(jLabelDescargando, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(301, 301, 301)
                        .addComponent(jLabelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPorciento, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelProgresoDescargaLayout.setVerticalGroup(
            jPanelProgresoDescargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgresoDescargaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProgresoDescargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescargando)
                    .addComponent(jLabelNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPorciento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarDescargaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jLabelNumero.getAccessibleContext().setAccessibleName("");

        jTextFieldCadenaBusquedaCancion.setToolTipText("");

        jButtonBuscarCancionPorTexto.setText("Buscar");
        jButtonBuscarCancionPorTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCancionPorTextoActionPerformed(evt);
            }
        });

        jButtonVerDetallesArtista.setText("Ver detalles y canciones del artista");
        jButtonVerDetallesArtista.setPreferredSize(new java.awt.Dimension(146, 23));
        jButtonVerDetallesArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerDetallesArtistaActionPerformed(evt);
            }
        });

        jLabel10.setText("Nombre artista");

        jLabelNombreArtista.setText("Nombre");

        javax.swing.GroupLayout jPanelDetallesArtistaLayout = new javax.swing.GroupLayout(jPanelDetallesArtista);
        jPanelDetallesArtista.setLayout(jPanelDetallesArtistaLayout);
        jPanelDetallesArtistaLayout.setHorizontalGroup(
            jPanelDetallesArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetallesArtistaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanelDetallesArtistaLayout.setVerticalGroup(
            jPanelDetallesArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetallesArtistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDetallesArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNombreArtista))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jButtonStopCancion.setText("Stop");
        jButtonStopCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopCancionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonVerDetallesArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelDetallesArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jButtonStopCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 11, Short.MAX_VALUE)
                                        .addComponent(jPanelProgresoDescarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(90, 90, 90))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTextFieldCadenaBusquedaCancion)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButtonVerCancionesSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(389, 389, 389)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonEscucharCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonBuscarCancionPorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadenaBusquedaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarCancionPorTexto))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEscucharCancion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonVerCancionesSistema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDetallesArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStopCancion)
                    .addComponent(jButtonVerDetallesArtista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProgresoDescarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jTabbedPaneConexion.addTab("Canciones", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTabbedPaneConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 773, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void windowClose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClose
        //Cerrar el cliente
        try {
            if(getCliente().getOut() != null && getCliente().getIn() != null)
                getCliente().cerrarCliente();
        } catch (IOException e) {
        }

        //Matamos el hilo
        if(getThr() != null)
            getThr().getThr().interrupt();
    }//GEN-LAST:event_windowClose

    private void jButtonVerDetallesArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerDetallesArtistaActionPerformed
        //Si no hay ninguna canción seleccionada, mostrar un mensaje de error
        if(jTableCancionesSistema.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una canción", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //Si hay más de una canción seleccionada, mostrar un mensaje de error
        else if(jTableCancionesSistema.getSelectedRowCount() > 1){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una única canción", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(jLabelNombreArtista.getText().equals(jTableCancionesSistema.getValueAt(jTableCancionesSistema.getSelectedRow(), 2).toString()) && jPanelDetallesArtista.isVisible()){
            //Si ya se está mostrando la información del artista, no hacer nada
        }
        else{
            //Obtener el id de la canción seleccionada
            jLabelNombreArtista.setText("");
            String idCancion = jTableCancionesSistema.getValueAt(jTableCancionesSistema.getSelectedRow(), 0).toString();
            getCliente().getOut().println(getControlador().generarCadenaVerDetallesArtistaCancion(getCliente(), idCancion));
            getCliente().getOut().flush();
            jPanelDetallesArtista.setVisible(true);
        }
    }//GEN-LAST:event_jButtonVerDetallesArtistaActionPerformed

    private void jButtonBuscarCancionPorTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCancionPorTextoActionPerformed
        String cadenaBusqueda = jTextFieldCadenaBusquedaCancion.getText().trim();
        jPanelDetallesArtista.setVisible(false);
        if(cadenaBusqueda.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor, introduzca una cadena de búsqueda", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            getCliente().getOut().println(getControlador().generarCadenaBuscarCancionPorTexto(getCliente(), cadenaBusqueda));
            getCliente().getOut().flush();
            jTextFieldCadenaBusquedaCancion.setText("");
        }
    }//GEN-LAST:event_jButtonBuscarCancionPorTextoActionPerformed

    private void jButtonEscucharCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscucharCancionActionPerformed
        //Si no hay ninguna canción seleccionada, mostrar un mensaje de error
        if(jTableCancionesSistema.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una canción", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //Si hay más de una canción seleccionada, mostrar un mensaje de error
        else if(jTableCancionesSistema.getSelectedRowCount() > 1){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una única canción", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //Obtener el id de la canción seleccionada
            String idCancion = jTableCancionesSistema.getValueAt(jTableCancionesSistema.getSelectedRow(), 0).toString();
            //Buscar si la canción ya está en el sistema cancion+idCancion+".mp3"
            try{
                String ruta = "cancion" + idCancion + ".mp3";
                if(Files.exists(Paths.get(ruta))){
                    getCliente().escucharCancion(Files.readAllBytes(Paths.get(ruta)));
                    System.out.println("Canción encontrada en el sistema: " + ruta);
                    getCliente().getOut().println(getControlador().generarCadenaGetSongFinished(idCancion, getCliente()));
                }
                else{
                    boolean descargando = false;
                    for(int i=0; !descargando && i<getThr().hilosCanciones.size(); i++){
                        if(getThr().hilosCanciones.get(i).idCancion.equals(idCancion)){
                            descargando = true;
                        }
                    }
                    if(!descargando){
                        //Si no está en el sistema ni se ha creado la hebra, pedir al servidor que la envíe
                        getCliente().getOut().println(getControlador().generarCadenaEscucharCancion(getCliente(), idCancion));
                        getCliente().getOut().flush();
                    }
                }
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_jButtonEscucharCancionActionPerformed

    private void jButtonVerCancionesSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerCancionesSistemaActionPerformed
        jPanelDetallesArtista.setVisible(false);
        getCliente().getOut().println(getControlador().generarCadenaGetCancionesSistema(getCliente()));
        getCliente().getOut().flush();
    }//GEN-LAST:event_jButtonVerCancionesSistemaActionPerformed

    private void jButtonVerUsuariosConectadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerUsuariosConectadosActionPerformed
        getCliente().getOut().println(getControlador().generarCadenaGetUsuariosConectados(getCliente()));
        getCliente().getOut().flush();
    }//GEN-LAST:event_jButtonVerUsuariosConectadosActionPerformed

    /**
     * @brief Método que se ejecuta al pulsar el botón de conectar
     * @param evt   Evento de pulsar el botón de conectar
     */
    private void buttonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConectarActionPerformed
        //Comprobar que ninguno de los campos esté vacío
        if(jTextFieldIP.getText().isEmpty() || jTextFieldPuerto.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor, rellene todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //Comprobar que el puerto sea un número
            try{
                //Comprobar que el puerto tiene un valor válido
                if(Integer.parseInt(jTextFieldPuerto.getText().trim()) < 0 || Integer.parseInt(jTextFieldPuerto.getText().trim()) > 9999){
                    JOptionPane.showMessageDialog(this, "El puerto debe ser un número entre 0 y 9999", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    try {
                        cliente.conectar(jTextFieldIP.getText().trim(), Integer.parseInt(jTextFieldPuerto.getText().trim()));
                        jTextAreaMensajesRecibidos.append("Conexión establecida con el servidor\n\n");
                        setThr(new LeerServidorThread(cliente, jTextAreaMensajesRecibidos, jTableUsuariosConectados, jTableCancionesSistema, jPanelProgresoDescarga, jLabelNumero, jProgressBarDescargaCancion, jLabelNombreArtista));
                        getThr().getThr().start();
                    } catch (IOException e) {
                        JOptionPane.showMessageDialog(this, "No se ha podido conectar con el servidor", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                    //Habilitar el campo de texto para enviar mensajes
                    jTextFieldMensajeEnviar.setEnabled(true);
                    buttonEnviar.setEnabled(true);

                }

            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "El puerto debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonConectarActionPerformed

    private void jButtonDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesconectarActionPerformed
        if(getCliente().getOut() != null && getCliente().getIn() != null){
            getCliente().getOut().println(getControlador().generarCadenaLogout(getCliente()));
            getCliente().getOut().flush();
        }

        //Eliminar las filas de la tabla de usuarios conectados
        while(jTableUsuariosConectados.getRowCount() > 0){
            ((javax.swing.table.DefaultTableModel) jTableUsuariosConectados.getModel()).removeRow(0);
        }

        //Eliminar las filas de la tabla de canciones del sistema
        while(jTableCancionesSistema.getRowCount() > 0){
            ((javax.swing.table.DefaultTableModel) jTableCancionesSistema.getModel()).removeRow(0);
        }

        //Limpia el área de mensajes recibidos
        jTextAreaMensajesRecibidos.setText("");

        jTextFieldMensajeEnviar.setEnabled(false);
        buttonEnviar.setEnabled(false);
    }//GEN-LAST:event_jButtonDesconectarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Comprobar que ninguno de los campos esté vacío
        if(jTextFieldLogin.getText().isEmpty() || jTextFieldContrasenia.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor, rellene todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            getCliente().setLogin(jTextFieldLogin.getText());
            getCliente().getOut().println(getControlador().generarCadenaLogin(getCliente().getLogin(), jTextFieldContrasenia.getText()));
            getCliente().getOut().flush();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @brief Método que se ejecuta al pulsar el botón de enviar
     * @param evt   Evento de pulsar el botón de enviar
     */
    private void buttonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnviarActionPerformed
        if (!jTextFieldMensajeEnviar.getText().isEmpty()){
            getCliente().getOut().println(jTextFieldMensajeEnviar.getText());
            getCliente().getOut().flush();
            jTextFieldCadenaBusquedaCancion.setText("");
        }
        jTextFieldMensajeEnviar.setText("");
    }//GEN-LAST:event_buttonEnviarActionPerformed

    private void jTableCancionesSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCancionesSistemaMouseClicked
        if(evt.getClickCount() == 2){
            jButtonEscucharCancionActionPerformed(null);
        }
    }//GEN-LAST:event_jTableCancionesSistemaMouseClicked

    private void jButtonStopCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopCancionActionPerformed
        try {
            getCliente().stopCancion();
        } catch (IOException e) {
            System.out.println("Error al parar la canción.");
        }
    }//GEN-LAST:event_jButtonStopCancionActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConectar;
    private javax.swing.JButton buttonEnviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscarCancionPorTexto;
    private javax.swing.JButton jButtonDesconectar;
    private javax.swing.JButton jButtonEscucharCancion;
    private javax.swing.JButton jButtonStopCancion;
    private javax.swing.JButton jButtonVerCancionesSistema;
    private javax.swing.JButton jButtonVerDetallesArtista;
    private javax.swing.JButton jButtonVerUsuariosConectados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDescargando;
    private javax.swing.JLabel jLabelNombreArtista;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelPorciento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDetallesArtista;
    private javax.swing.JPanel jPanelProgresoDescarga;
    private javax.swing.JProgressBar jProgressBarDescargaCancion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneConexion;
    private javax.swing.JTable jTableCancionesSistema;
    private javax.swing.JTable jTableUsuariosConectados;
    private javax.swing.JTextArea jTextAreaMensajesRecibidos;
    private javax.swing.JTextField jTextFieldCadenaBusquedaCancion;
    private javax.swing.JTextField jTextFieldContrasenia;
    private javax.swing.JTextField jTextFieldIP;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldMensajeEnviar;
    private javax.swing.JTextField jTextFieldPuerto;
    // End of variables declaration//GEN-END:variables
}
